version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.1.0
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3,sqs,secretsmanager
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "./local/data/localstack:/var/lib/localstack"
      - "./local/localstack:/etc/localstack/init/ready.d/"
      - "/var/run/docker.sock:/var/run/docker.sock"
